
spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/adv_microservice
      username: root
      password: root
  jpa:
      hibernate.ddl-auto: update
      show-sql: true