
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      database: ProductService
      port: 27017
server:
    port : 8084
eureka:
  client:
    instance:
      prefer-ip-address: true
    serviceUrl:
      defaultZone: http://localhost:9761/eureka
